Spazzy757/paul

- Dockerfile
- cmd/paul/main.go
- go.mod
- go.sum
- manifests/base/deployment.yaml
- manifests/base/service.yaml
- pkg/github/pullrequests.go
- pkg/github/pullrequests_test.go
- pkg/helpers/helpers.go
- pkg/router/router.go
Added a basic webserver that will handle Github requests
> Added basic webserver

- go.mod
- go.sum
- pkg/config/config.go
- pkg/config/config_test.go
- pkg/helpers/helpers.go
- pkg/helpers/helpers_test.go
Added a bunch of helper authentication functions to help with the App setup
> Added setup for the authentication process

- PAUL.yaml
- go.mod
- go.sum
- pkg/github/client.go
- pkg/github/pullrequests.go
- pkg/github/webhooks.go
- pkg/types/types.go
- pkg/types/types_test.go
- Added the ability to read `PAUL.yaml` config from root directory
- Added `PAUL.yaml`
- Refactored code to be cleaner and seperated logic into files
> Updated Paul to be able to read Yaml Config

- .github/workflows/tests.yaml
- README.md
- Added a CI/CD test for issue: https://github.com/Spazzy757/paul/issues/3
- Update Readme for issue: https://github.com/Spazzy757/paul/issues/13
> Feature add CI/CD and Update Readme

- pkg/animals/cats.go
- pkg/animals/dogs.go
- pkg/animals/helpers.go
- pkg/github/pullrequests.go
- pkg/github/webhooks.go
- pkg/helpers/helpers.go
- pkg/router/router.go
- pkg/types/types.go
- Added small descriptions to the exported functions that were throwing the golint errors
- Did not change any function definitions or implementations 
- Can add to the exported types and function definitions to make them more descriptive
Goreport for golint improved from 50% to 90%. https://goreportcard.com/report/github.com/suramrit/paul
The remaining warnings are around function definitions which I have not changed
> Fix Golint warning Issue

- pkg/github/client.go
- pkg/github/client_test.go
- pkg/github/issue.go
- pkg/github/pullrequests.go
- Added the functionality to fetch the `PAUL.yaml` from the default branch
issue: https://github.com/Spazzy757/paul/issues/20
> Added default branch functionality

- PAUL.yaml
- pkg/github/issue.go
- pkg/github/issue_test.go
- pkg/types/types.go
- pkg/types/types_test.go
- Added the functionality to use the `/label` command
- Added the functionality to use the `/remove-label` command
Related Issue: https://github.com/Spazzy757/paul/issues/16
> Added functionality to label issues

- PAUL.yaml
- README.md
- pkg/github/issue.go
- pkg/github/pullrequests.go
- pkg/github/pullrequests_test.go
- pkg/github/webhooks_test.go
- pkg/test/client.go
- pkg/types/types.go
- pkg/types/types_test.go
- Adds the ability to limit the amount of Pull Requests that a User can have opened at any time. Paul will close any PR's that get opened over the limit
> Added Pull Request Limiter

- pkg/github/pullrequests.go
- pkg/github/pullrequests_test.go
- Updated action check to "closed"
- Added Check for Merge
> Fixed branch destroyer

- README.md
- mocks/merge-command.json
- pkg/github/issue.go
- pkg/github/issue_test.go
- pkg/github/pullrequests.go
- pkg/github/pullrequests_test.go
- Added the `/merge` command in order to allow maintainers to merge Pull Requests
> Added the merge command

- pkg/github/issue.go
- pkg/github/issue_test.go
- Update Issue Comment Handler to have less complexity, movedlogic into the command handlers
> Clean up complexity of the Issue Comment Handler

- pkg/animals/animals.go
- pkg/router/router.go
- pkg/router/router_test.go
- pkg/test/client.go
- Fixes some Go Linting Errors
- Adds a bit more testing
> Go linter fix

- pkg/config/config.go
- pkg/github/issue.go
- pkg/github/issue_test.go
- pkg/types/types.go
- Fixed more Go Linting Errors
> Fixed more go linting errors

- PAUL.yaml
- pkg/client/client.go
- pkg/github/issue_test.go
- pkg/github/pullrequests.go
- pkg/github/schedules.go
- pkg/github/schedules_test.go
- pkg/scheduler/scheduler.go
- pkg/types/types.go
- pkg/types/types_test.go
* Add feature to merge pull requests labelled with the `merge` label
> Feature Scheduled Merges

- pkg/github/issue_test.go
- pkg/github/pullrequests_test.go
- pkg/github/schedules_test.go
- pkg/github/webhooks_test.go
* Ignored error checking in some tests
> Fixed golang linting errors

- README.md
* Added instructions on automated merges
> Added new instructions to README

- pkg/github/schedules.go
* Removed check for Mergeable as Github doesn't provide the information when fetching Pull Requests
> Automated Merge fix

- pkg/config/config.go
- pkg/config/config_test.go
- Added Paul looking in the `.github` directory
fixes: https://github.com/Spazzy757/paul/issues/59
> Added a check for the PAUL.yaml in the .github directory

- .github/PAUL.yaml
- mocks/giphy-command.json
- pkg/animals/animals_test.go
- pkg/gif/gif.go
- pkg/gif/gif_test.go
- pkg/github/issue.go
- pkg/github/issue_test.go
- pkg/types/types.go
- pkg/types/types_test.go
- adds the `/giphy` command to Paul
fix: https://github.com/Spazzy757/paul/issues/69
> Added Giphy Command

- README.md
- updated README with /giphy comand instructions
> Updated README with /giphy command

- .github/workflows/codeql-analysis.yml
- added codeQL Scanning action
> create codeql analysis workflow

- .github/PULL_REQUEST_TEMPLATE/maintainer.md
- Added Pull Request Templates
> Feature pull request template

- pkg/router/router.go
- Changes the route path `/` to be used for website
- Removes the unneeded path
fix: https://github.com/Spazzy757/paul/issues/19
> Updated routing to server website on route path

- .github/PAUL.yaml
- pkg/github/checks.go
- pkg/github/checks_test.go
- pkg/github/pullrequests.go
- pkg/github/pullrequests_test.go
- pkg/github/webhooks_test.go
- pkg/helpers/helpers.go
- pkg/types/types.go
- pkg/types/types_test.go
* Adds the DCO check
fix: None
> Added DCO Check

- pkg/config/config.go
- pkg/config/config_test.go
Signed-off-by: Spazzy <brendankamp757@gmail.com>
- If paul cant find the PAUL.yaml file in the repo, he will just skip all the checks without throwing and error
fix: https://github.com/Spazzy757/paul/issues/92
> Fixed error when cant find Paul Config

- PRIVACY_POLICY.md
- README.md
- Adds a privacy policy in preparation of going to Marketplace
fix: https://github.com/Spazzy757/paul/issues/90
> Feature privacy policy

- .github/PAUL.yaml
- pkg/github/checks.go
- pkg/github/checks_test.go
- pkg/github/pullrequests.go
- pkg/github/pullrequests_test.go
- pkg/types/types.go
- pkg/types/types_test.go
Signed-off-by: Spazzy <brendankamp757@gmail.com>
- Adds a check that looks at commits and fails if commits are not verified
fix: None
> Added check for verified commits

- pkg/config/config.go
- pkg/config/config_test.go
- pkg/github/checks.go
Signed-off-by: Spazzy <brendankamp757@gmail.com>
- stop returning error if failure to donwload `PAUL.yaml`
- Fix invalid state of checks
fix: https://github.com/Spazzy757/paul/issues/92
> bug fix for failing to download config

- go.mod
- go.sum
- pkg/client/client.go
- pkg/client/client_test.go
- pkg/config/config.go
- pkg/github/checks.go
- pkg/github/checks_test.go
- pkg/github/issue.go
- pkg/github/issue_test.go
- pkg/github/pullrequests.go
- pkg/github/pullrequests_test.go
- pkg/github/schedules.go
- pkg/github/schedules_test.go
- pkg/github/webhooks.go
- pkg/router/router.go
- pkg/scheduler/scheduler.go
- pkg/test/client.go
Signed-off-by: Spazzy <brendankamp757@gmail.com>
- updates go-github v35 => v36
fix: https://github.com/Spazzy757/paul/issues/180
> updated go-github v35 => v36
